// https://www.pokemon.cn/play/pokedex/api/v1?pokemon_ability_id=&zukan_id_from=1&zukan_id_to=898

// Generated by https://quicktype.io
// Generated by https://quicktype.io

import 'package:flutter/cupertino.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:pokedex/http/api.dart';
import 'package:pokedex/module/pokemon_types.dart';

part 'pokemon.g.dart';

/*
{
  "zukan_id": "001",
  "zukan_sub_id": 0,
  "pokemon_name": "妙蛙种子",
  "pokemon_sub_name": "",
  "weight": 6.9,
  "height": 0.7,
  "file_name": "/img/pm/cf47f9fac4ed3037ff2a8ea83204e32aff8fb5f3.png",
  "pokemon_type_id": "grass,poison",
  "pokemon_type_name": "草,毒"
}
*/
@JsonSerializable()
class Pokemon {
  @JsonKey(name: 'zukan_id')
  String zukanId;
  @JsonKey(name: 'zukan_sub_id')
  int zukanSubId;
  @JsonKey(name: 'pokemon_name')
  String pokemonName;
  @JsonKey(name: 'pokemon_sub_name')
  String pokemonSubName;
  double weight;
  double height;
  @JsonKey(name: 'file_name')
  String fileName;
  @JsonKey(name: 'pokemon_type_id')
  String pokemonTypeId;
  @JsonKey(name: 'pokemon_type_name')
  String pokemonTypeName;

  Pokemon({
    required this.zukanId,
    required this.zukanSubId,
    required this.pokemonName,
    required this.pokemonSubName,
    required this.weight,
    required this.height,
    required this.fileName,
    required this.pokemonTypeId,
    required this.pokemonTypeName,
  });

  factory Pokemon.fromJson(Map<String, dynamic> json) =>
      _$PokemonFromJson(json);

  Map<String, dynamic> toJson() => _$PokemonToJson(this);

  String get thumbnailImage => '${API.RESOURCES_URL}$fileName';

  List<String> get typeIds => pokemonTypeId.split(',');

  List<String> get typeNames => pokemonTypeName.split(',');

  List<PokemonTypes> get pokemonTypes =>
      typeIds.map((type) => PokemonTypes.formName(type)).toList();

  Color get color => pokemonTypes.first.color;
}
